<?php

namespace admin\controller;

use framework\core\Controller;

class AttachmentManagerController extends Controller
{
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub

        // id
        $aid = "";
        if (isset($_GET["id"])){
           $aid =  $_GET["id"];
        }
        $this->data["aid"] = $aid;

        // tbName
        $tbName = "";
        if (isset($_GET["tbName"])){
            $tbName =  $_GET["tbName"];
        }
        $this->data["tbName"] = $tbName;

        // 账户名
        $accName = "";
        if (isset($_GET["accName"])){
            $accName =  $_GET["accName"];
        }
        $this->data["accName"] = $accName;

        $this -> loadTemplate(["data"=>$this -> data],"attachment/index.html");
    }
}