<?php

namespace admin\controller;

use framework\core\Controller;

class GeneralInfoController extends Controller
{
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
        $this -> loadTemplate(["data"=>$this -> data],"general/index.html");
    }
}